# Generated by Django 5.1.4 on 2025-01-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoVotant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('datenaissance', models.DateField()),
                ('identification', models.CharField(max_length=50)),
                ('bulltinvote', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeVotant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('datenaissance', models.DateField()),
                ('identification', models.CharField(max_length=50)),
                ('bulltinvote', models.CharField(max_length=50)),
            ],
        ),
    ]
