# Generated by Django 5.1.4 on 2025-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covotant',
            name='date_vote',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='devotant',
            name='date_vote',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='covotant',
            name='bulltinvote',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='covotant',
            name='identification',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='devotant',
            name='bulltinvote',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='devotant',
            name='identification',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
